### ISSUE TITLE
what name to use for a validator to test a body directly composed of an array

### ISSUE THREAD

**Issue by ldom** [svanoort/pyresttest#107]
Hi Sam,

Thanks for this great tool.

I'm trying to test the result of an endpoint that directly returns and array of objects:
`[{'id': '1', 'name': 'whatever'}, {'id': '2', 'name': 'another name'}]`

What do I need to use in the validator?

This is what I'm using in some of the other tests:
`- compare: {jsonpath_mini: "<proper-path>", comparator: "count_eq", expected: 2}`

but I'm not sure what to use in lieu of "proper-path" in that case.

Thanks,
Laurent

**Comment by svanoort** [comment]
Hi Laurent, 
The best way to do this is to define two extract/test validators checking for the elements:

```yaml
- assertTrue: {jsonpath_mini: "0.name", test: 'exists'}
- assertTrue: {jsonpath_mini: "1.name", test: 'exists'}
```

The next release (a few months out) will include a better way to do this in one line with top-level JSON elements: (https://github.com/svanoort/pyresttest/pull/106):
```yaml
- compare: {jsonpath_mini: "", comparator: "count_eq", expected: 2}
```

In the further future, the jsonpath_mini feature will get a more powerful sibling, in the form of a JsonPath-RW extractor (Issue open to add that here: https://github.com/svanoort/pyresttest/issues/78 ).

I hope that helps answer your question?

Thanks!
Sam

**Comment by ldom** [comment]
That answers the question perfectly, thank you very much.

**Comment by svanoort** [comment]
Excellent!  I'm going to go ahead and close this issue out, and work on getting that into the master branch.

**Comment by svanoort** [comment]
@ldom You might be interested to know that this is now finished and merged into master, with the syntax at bottom preferred.  It's not released on pip yet (I do more exhaustive cross-environment & installation testing for each release), but you can clone and run or build from source!

```yaml
- compare: {jsonpath_mini: ".", comparator: "count_eq", expected: 2}
```

Cheers!
