### ISSUE TITLE
Feature request: Validate response headers

### ISSUE THREAD

**Issue by sjagoe** [svanoort/pyresttest#11]
It would be useful in my case to be able to validate that a server is returning a response of the correct type before validating the actual request body.

**Comment by svanoort** [comment]
Finally got around to documenting and merging this in. *sigh*

**Comment by trigunam** [comment]
We started working on pyresttest and on our initial look at the module its a great way to test. Kudos for this tool.

We have a question on header validation. Whenever we try to use the header validations as mentioned here, get a trace as follows (Is the implementations mentioned in this issue already part of the latest pyresttest module?):

ERROR:Test Failure, failure type: Extractor Exception, Reason: Extractor threw exception
ERROR:Validator/Error details:Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyresttest\validators.py", line 358, in validate
    body=body, headers=headers, context=context)
  File "C:\Python27\lib\site-packages\pyresttest\validators.py", line 185, in extract
    return self.extract_internal(query=query, body=body, headers=headers, args=self.args)
  File "C:\Python27\lib\site-packages\pyresttest\validators.py", line 280, in extract_internal
    raise ValueError("Invalid header name {0}".format(query))
ValueError: Invalid header name Content-Type
