### ISSUE TITLE
Body as a file name in yaml

### ISSUE THREAD

**Issue by renjithmenon** [svanoort/pyresttest#110]
Found pyresttest really useful !
I have a bunch of complex json files , so wanted to check if i can use the -body as a variable in yaml and point to these files for each test cases 

Thanks in Advance

**Comment by svanoort** [comment]
Glad you're finding it helpful!   Yes, this feature is supported and battle-tested -- here's an example in the tests: https://github.com/svanoort/pyresttest/blob/master/pyresttest/content-test.yaml#L90-L104

This will read the file using a variable to give the file path, and then use it as the HTTP request body. 
One convenient note: the file is read directly as binary, so you can use this for any encoding (including raw binary image data).

**Comment by renjithmenon** [comment]
Excellent ! Thanks for your quick response .

I will try this and will let you know .

**Comment by svanoort** [comment]
@renjithmenon I'm going to go ahead and close out the issue for now, since it sounds like your question is answered.  But, I'd be happy to reopen if you have issues or more questions on this!
