### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by renjithmenon** [svanoort/pyresttest#112]
I frequently get the following timeout error - how do I increase the timeout  ?

/resttest/lib/python2.7/site-packages/pyresttest/resttest.py", line 319, in run_test
    curl.perform()  # Run the actual call
error: (28, 'Operation timed out after 10003 milliseconds with 0 bytes received')

**Comment by svanoort** [comment]
Hi!  Yes, there's a timeout option at the test config level!  So, within a testset, what you'd do is:

```yaml
- config:
  - testset: "Existing options for config"
  - timeout: 60000
```

Does that solve your problem?  I will say if you're hitting a 10 second timeout *often* that means larger issues are being encountered (something is wrong in communication) -- that's worth looking into with a traditional Curl call (and using -verbose) mode to see if it will respond normally.

**Comment by renjithmenon** [comment]
Thanks a lot !  Changing the timeout Worked .

I face another issue occasionally in son validation when passing the body as a son file . Is there way by which I can explicitly pass the file as Binary file ? My jsons has a lot of nested parenthesis - i suspect the parsing by file.read() is creating the issue .

--Renjith-

**Comment by svanoort** [comment]
Renjith, 
I'm not sure exactly what you mean?  You can read a *request body* from a file as shown in [the example here](https://github.com/svanoort/pyresttest/blob/master/pyresttest/content-test.yaml#L81).  If you want to just take the JSON as raw binary content from a *response body* you can do that with the [raw_body extractor type](https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md#extractor-raw_body) that was added in the last release.  It works the same as the jsonpath_mini extractor except the query argument is ignored and the extractor returns the entire content (so you can use the regex and contains operators).

In this case, file.read() doesn't do any parsing internally, it's just a binary read of data.

Does that answer your question?

- Sam

**Comment by svanoort** [comment]
@renjithmenon  Hi, does the above answer your question?  I'd like to be able to close out this issue, if so!

**Comment by renjithmenon** [comment]
Thanks a lot ! this answers my question
