### ISSUE TITLE
Question - Does pyresttest parse hal+json responses - I am only seeing empty or null arrays for the _links and _embedded items when I print out the bodies

### ISSUE THREAD

**Issue by joykrogers** [svanoort/pyresttest#119]
I am having trouble getting the comparator to work when I am using hal+json format.  The _links items and _embedded items are empty or null when I print out the bodies with pyresttest.  I have checked in Postman and can get the _links and _embedded values back.  I may be doing something wrong with the comparator.  

partial example of output:  .... "469023650","_links":[],"_embedded":null}

Below is a generic example of some json and how I would write the compare test. Just checking to see if this should work with pyresttest.

example json:

{
    "_links": {
        "self": {
            "href": "http://example.org/api/user/matthew"
        }
    }
    "id": "matthew",
    "name": "Matthew Weier O'Phinney",
    "_embedded": {
        "contacts": [
            {
                "_links": {
                    "self": {
                        "href": "http://example.org/api/user/mac_nibblet"
                    }
                },
                "id": "mac_nibblet",
                "name": "Antoine Hedgecock"
            },
            {
                "_links": {
                    "self": {
                        "href": "http://example.org/api/user/spiffyjr"
                    }
                },
                "id": "spiffyjr",
                "name": "Kyle Spraggs"
            }
        ],
        "website": {
            "_links": {
                "self": {
                    "href": "http://example.org/api/locations/mwop"
                }
            },
            "id": "mwop",
            "url": "http://www.mwop.net"
        },
    }
}

example pyresttest (partial)

- test: # get hal info
    - name: "Get hal info"
    - url: "someurl/api/forms"
    - method: "GET"
    - headers: {'Accepts': 'application/hal+json'}
    - body: {'template':'token=$ACCESS_TOKEN'}
    - expected_status: [200]
    - validators:
		- compare: {jsonpath_mini: '_links.self.href', comparator: 'str_eq', expected:   'http://example.org/api/user/matthew'}}
		- compare: {jsonpath_mini: 'id', comparator: 'str_eq', expected:  {'matthew'}
		- compare: {jsonpath_mini:  '_embedded.contacts.0._links.self.href", comparator: 'eq', expected:   'http://example.org/api/user/mac_nibblet'}

**Comment by svanoort** [comment]
Hi @joykrogers -- it looks like the problem here is invalid JSON, specifically a single misplaced comma (oops!):

Specifically the comma that should have been at the closing brace before "id":"matthew" was instead after `"url": "http://www.mwop.net"}`

Once corrected like so, it will parse correctly:
```json
{
    "_links": {
        "self": {
            "href": "http://example.org/api/user/matthew"
        }
    },
    "id": "matthew",
    "name": "Matthew Weier O'Phinney",
    "_embedded": {
        "contacts": [
            {
                "_links": {
                    "self": {
                        "href": "http://example.org/api/user/mac_nibblet"
                    }
                },
                "id": "mac_nibblet",
                "name": "Antoine Hedgecock"
            },
            {
                "_links": {
                    "self": {
                        "href": "http://example.org/api/user/spiffyjr"
                    }
                },
                "id": "spiffyjr",
                "name": "Kyle Spraggs"
            }
        ],
        "website": {
            "_links": {
                "self": {
                    "href": "http://example.org/api/locations/mwop"
                }
            },
            "id": "mwop",
            "url": "http://www.mwop.net"
        }
    }
}
```

It looks like the issue is present in the original too -- whoops!  http://phlyrestfully.readthedocs.org/en/latest/halprimer.html

You can test this in the python like so, after saving the corrected json to 'jsondoc.json':

```python
json_text = open('jsondoc.json').read()
json_obj = json.loads(json_text)
query1 = '_links.self.href'
query2 = 'id'
query3 = '_embedded.contacts.0._links.self.href'
pyresttest.validators.MiniJsonExtractor.query_dictionary(query1, json_obj)
pyresttest.validators.MiniJsonExtractor.query_dictionary(query2, json_obj)
pyresttest.validators.MiniJsonExtractor.query_dictionary(query3, json_obj)
```

Output:
```
>>> json_text = open('jsondoc.json').read()
>>> json_obj = json.loads(json_text)
>>> query1 = '_links.self.href'
>>> query2 = 'id'
>>> query3 = '_embedded.contacts.0._links.self.href'
>>> pyresttest.validators.MiniJsonExtractor.query_dictionary(query1, json_obj)
u'http://example.org/api/user/matthew'
>>> pyresttest.validators.MiniJsonExtractor.query_dictionary(query2, json_obj)
u'matthew'
>>> pyresttest.validators.MiniJsonExtractor.query_dictionary(query3, json_obj)
u'http://example.org/api/user/mac_nibblet'
```

You should see some errors in the PyRestTest output due to the invalid JSON input here. 
Side note: the trailing comma after the closing brace is against the JSON spec but *some* parsers in browsers silently ignore it (Python doesn't). 

Thanks for using PyRestTest, and I hope that answers your question?

Cheers,
Sam

**Comment by svanoort** [comment]
@joykrogers  I'm going to go ahead and close this one out, if you have no objections, since I think the question has been answered?  (Let me know if not, we can certainly re-open/investigate this more).

**Comment by joykrogers** [comment]
Thanks so much for the info above. 

I think I may be missing a package or something because when I run the commands above I get an error AttributeError: 'module' object has no attribute 'validators'.  I will do more research on my side.  I'm sure it is something with my environment that I do not have set correctly.

I am using python 2.7.  Here is the output I get:

python
Python 2.7.11 (default, Dec  5 2015, 14:44:47) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> import pyresttest
>>> json_text = open('jsondoc.json').read()
>>> json_obj = json.loads(json_text)
>>> query1 = '_links.self.href'
>>> query2 = 'id'
>>> query3 = '_embedded.contacts.0._links.self.href'
>>> pyresttest.validators.MiniJsonExtractor.query_dictionary(query1, json_obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'validators'
>>> pyresttest.validators.MiniJsonExtractor.query_dictionary(query2, json_obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'validators'
>>> pyresttest.validators.MiniJsonExtractor.query_dictionary(query3, json_obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'validators'
>>>

**Comment by svanoort** [comment]
@joykrogers  Your packages are fine, the issue is that the import is a bit particular (my fault for not including the full imports).  The below should work fine (testing with a fresh clone in an empty Docker container):

**Setup:**
```shell
git clone https://github.com/svanoort/pyresttest.git
cd pyresttest
python
```

**Python:**
```
import json
import pyresttest
from pyresttest import validators
json_text = open('jsondoc.json').read()
json_obj = json.loads(json_text)
query1 = '_links.self.href'
query2 = 'id'
query3 = '_embedded.contacts.0._links.self.href'
pyresttest.validators.MiniJsonExtractor.query_dictionary(query1, json_obj)
pyresttest.validators.MiniJsonExtractor.query_dictionary(query2, json_obj)
pyresttest.validators.MiniJsonExtractor.query_dictionary(query3, json_obj)
```

Does that work correctly for you?

**Comment by joykrogers** [comment]
That works.  Thanks so much.  My apologies for not understanding the import statements.
