### ISSUE TITLE
Test Installation In VirtualEnvs

### ISSUE THREAD

**Issue by svanoort** [svanoort/pyresttest#134]
Add installation testcase(s) for pip/pip develop mode installation in virtual environments

If easy, add documentation for this

**Comment by lerrua** [comment]
@svanoort in OSX i'm already using virtualenv, no problem here. 
Some linux distro like ubuntu works well, catarse build use ubuntu in CircleCI and also use virtualenv: https://circleci.com/gh/catarse/catarse-api-specs/90

**Comment by svanoort** [comment]
@lerrua Looks like it's working nicely here too across python 2 & 3 docker images (I think some of the installation fixes have resolved issues now).  Going to go ahead and close this one out, since it should be covered by pip testing.

**Comment by lerrua** [comment]
:+1:
