### ISSUE TITLE
Unable to run pyresttest

### ISSUE THREAD

**Issue by VikramBPurohit** [svanoort/pyresttest#136]
Hi There,

I never used python but this project is really interesting. I am trying to test services written in express.js
I am able to access Yaml file from browser URL but when I am trying to access using --URL and --test
Somehow resttest.py is not able to find yaml file.

Any help on understanding how resttest.py is trying to find a file would be greatly appreciated.

#help_wanted

**Comment by VikramBPurohit** [comment]
Hi,

I have created a sample express application for you to review. Yaml file is inside public/test folder.

https://github.com/VikramBPurohit/pyresttest-express.git

Below is the error I am getting when trying to run pyresttest -

![image](https://cloud.githubusercontent.com/assets/13356618/12040276/b01fb974-ae35-11e5-9fbc-9adbc20480b7.png)

Thanks in Advance.

**Comment by svanoort** [comment]
@VikramBPurohit When I try to run your test, I can't reproduce it on python 2.6, 2.7 or 3.4.3, I'm wondering what your current folder is?  Tests (and extensions) are loaded relative to the current working directory, it's a straight python file open. 

My steps:

```
# Clone pyresttest, go into the pyresttest folder
docker run --rm -it -v $(pwd):/pyresttest -w /pyresttest python:3.4.3 /bin/bash
# Now inside container
python setup.py install
cd /tmp
git clone https://github.com/VikramBPurohit/pyresttest-express.git
cd pyresttest-express 
pyresttest http://localhost:3000 public/test/test.yaml
```

What it will show is an error ending with:
```
found unexpected ':'
  in "<unicode string>", line 22, column 73:
     ... , comparator: contains, expected:'json'}
```
This is because it isn't valid YAML: you need a space between keys and values in a YAML dictionary, or quotes around it.

**Comment by VikramBPurohit** [comment]
Thanks Sam for your respone! @svanoort  @svanoort-jenkins 

I have 2 linux boxes.

Box 1 - Installed PyRestTest
Box 2 - Installed nodejs service which I uploaded 
(https://github.com/VikramBPurohit/pyresttest-express.git)

When I am doing CURL from Box 1 to URL, I can see the YAML file. Service is hosted on 9061 in this case.

![image](https://cloud.githubusercontent.com/assets/13356618/12056808/f681d0a4-af08-11e5-8782-189fa7f5d4bc.png)


But when I am running  pyresttest http://10.206.150.98:9061 public/test/test.yaml

![image](https://cloud.githubusercontent.com/assets/13356618/12056818/1627305c-af09-11e5-8a6c-273d3cbd5934.png)

In above error message, I am printing  which is relative - "public/test/test.yaml" which can't be open from remote machine..

![image](https://cloud.githubusercontent.com/assets/13356618/12056850/8a76a276-af09-11e5-93be-26c0e757a1a1.png)



![image](https://cloud.githubusercontent.com/assets/13356618/12056802/d4ca888e-af08-11e5-9ff9-48fb88b022e3.png)

**Comment by VikramBPurohit** [comment]
Hi @svanoort 
Please ignore this. I just realize the path is actually of local machine not remote machine where service has been deployed. From last 2 days, I was under impression that yaml file will be available with service but it is with pyresttest :)

Thanks again for help and Happy new year in advance!

**Comment by svanoort** [comment]
@VikramBPurohit  Sounds good -- I thought it sounded a little odd what you described!  Glad you're sorted out, and happy new year and happy PyRestTesting to you too!  :)
