### ISSUE TITLE
Bug in 'curl_option_' parsing

### ISSUE THREAD

**Issue by jcelliott** [svanoort/pyresttest#138]
The usage of `string.lstrip` in [tests.py](https://github.com/svanoort/pyresttest/blob/master/pyresttest/tests.py#L521) is incorrect. [The documentation for `lstrip`](https://docs.python.org/2/library/stdtypes.html#str.lstrip) specify that the argument is "the set of characters to be removed" **not** a string prefix to be removed. The result is that if you specify, e.g., `curl_option_timeout` you get the following error message:

    ValueError: Illegal curl option: MEOUT

after the 't' and 'i' in 'timeout' were stripped.

**Comment by svanoort** [comment]
Good catch, thank you @jcelliott 

I've added tests to cover this, plus a fix (and credit for discovering it in the changelog) with https://github.com/svanoort/pyresttest/commit/0d3c793892422c1f5e57f9bf2f25eee4054d53d4
