### ISSUE TITLE
username:password generation is broken in python3.5.1

### ISSUE THREAD

**Issue by astrickhart** [svanoort/pyresttest#139]
I am running the latest master code in python 3.5.1.  I was getting good results in python 2.7 with the pip install, but when I tried the same test case in 3.5.1 and pyresttest master, I got 401 HTTP responses

When tests.py line 313 constructs the "username:password" string for the curl object, it is generating:
b'username':b'password'

Changing line that line locally to:
curl.setopt(pycurl.USERPWD, self.auth_username + b':' + self.auth_password)
fixed the problem, and now I generate:
b'username:password'

I'm not too familiar with unicode/binary details, so that might not be a good actual fix, but it reveals the issue.

**Comment by svanoort** [comment]
Thank  for reporting this, @astrickhrart - looks like an easy fix (string/binary formatting issue in Py3 only). Should be an easy fix, I'll do the fix and include it in this upcoming release, which is when Py3 support becomes available by pip.

**Comment by svanoort** [comment]
@astrickhart Apologies for the delay, this should be fixed by this PR:  https://github.com/svanoort/pyresttest/pull/154

I'm going to go ahead and close the issue, since I've tested the fix, but please reply back if I've somehow missed something. 

Thanks!
