### ISSUE TITLE
Feature request for commandline option to set DEFAULT_TIMEOUT

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#145]
Noticed that sometimes the cURL requests would fail because it would hit the 10 second DEFAULT_TIMEOUT. 

It would be convenient if we could set the timeout in the YAML file and / or in a commandline switch.

I manually changed my timeout to be 20 seconds.

**Comment by svanoort** [comment]
You can override this with curl_option_timeout in the test, or by setting 'timeout' in the test config element.  This would be nice to add add a command-line option too, yes (possibly tied to scoping changes).

**Comment by nitrocode** [comment]
Oh I didn't realize that it was configurable. That makes it much easier! Thanks
