### ISSUE TITLE
Standardized output

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#150]
My substep names were not being printed out even with the verbose flag set. Would you add an option to output the results of the test(s) to a standardized output like TAP ([Test Anything Protocol](https://testanything.org/)) ?

This would make it much easier more reporting and incorporating into jenkins by use of their [TAP plugin](https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin).

**Comment by svanoort** [comment]
@nitrocode https://github.com/svanoort/pyresttest/issues/43 - a version of this is already in the medium-term roadmap (via xUnit output).  Please consult existing issues before opening a new one. 

Thanks,
Sam

**Comment by nitrocode** [comment]
@svanoort my mistake. Thanks for showing me a previously written enhancement
