### ISSUE TITLE
Document JsonSchema Extension & installation of library to use

### ISSUE THREAD

**Issue by nitrocode** [svanoort/pyresttest#151]
Just noticed when stepping through resttest.py that the pip module jsonschema was missing and the documentation does not mention it

**Comment by svanoort** [comment]
@nitrocode this is intentional.  You are supposed to be able to install without jsonschema, and the schema features are option (available only if that module is installed).

**Comment by nitrocode** [comment]
I just meant there wasn't any documentation on the front page to know to install it. I found out by stepping through it and saw there was a logging.debug() message that was printed however I did not have logging=debug on.

**Comment by svanoort** [comment]
@nitrocode Fair, adding a note to better document JsonSchema extension use and installation

**Comment by svanoort** [comment]
Covered by commit: https://github.com/svanoort/pyresttest/commit/0afd87978c3ea6dd65853d3c75191c06d6d4b5cb
