### ISSUE TITLE
Setting timeout for the Curl call.

### ISSUE THREAD

**Issue by uknth** [svanoort/pyresttest#166]
I couldn't find a hook/documentation by which I could increase the default timeout of the curl call. The problem I have is, my API request is expected to take more than 10 secs, and the test case throws error because of it. 
I apologies in advance if I am missing something obvious here.

**Comment by spradeepv** [comment]
Following configuration would increase the default timeout:

---
```
- config:
    - testset: "Quickstart app tests"
    - timeout: 600000
```

I hope this is what you are looking for!!

**Comment by spradeepv** [comment]
The following configuration would increase the timeout for each tests. Hope this helps.

```
---
- config:
    - testset: "Quickstart app tests"
    - timeout: 600000

```

**Comment by uknth** [comment]
Thanks, this worked!
