### ISSUE TITLE
Question: May config as global one ?

### ISSUE THREAD

**Issue by IVANOPT** [svanoort/pyresttest#172]
Hi, svanoort:

During the development, I have some yamls with the same config `- config: ...` . So far, I've added the config to each yaml, but they are duplicate. If there is a way to write a basis file and import it multiple times? 

Thanks.

**Comment by svanoort** [comment]
HI @IVANOPT , 
Unfortunately this is not supported yet, however the upcoming work on [support for making all properties dynamic](https://github.com/svanoort/pyresttest/issues/101) should cover what you're looking for. 

Which particular variables were you looking to share between tests?  There's not that much which is of interest in the config element itself (maybe variable declarations, but you can define those as command line arguments).  Timeout could probably be added as a command-line argument very easily, if that's of interest.

Cheers, 
Sam

**Comment by IVANOPT** [comment]
Thank for your explanation and I'll try to use command-line, meanwhile looking forward to the new release.

**Comment by svanoort** [comment]
Absolutely!  Chugging away on this + enabling JUnit output whenever I get time. I'll go ahead and close this one out, and keep plugging on the steps towards 1.8/1.9.
