### ISSUE TITLE
[Information] Atom package for pyresttest

### ISSUE THREAD

**Issue by BastienAr** [svanoort/pyresttest#179]
I have quickly developed an [atom](https://atom.io/) package to add syntax highlighting and some snippets for pyresttest files. Thought it  may be useful for users.

[language-pyresttest](https://atom.io/packages/language-pyresttest)

**Comment by svanoort** [comment]
@BastienAr This looks great, thank you for putting this together!   I'll add a ref to the main README so others know about it.

**Comment by svanoort** [comment]
@BastienAr Added ref with https://github.com/svanoort/pyresttest/pull/186/commits/2884f2fc687b70125309033f5bacc1e493fcbdfd - so I am closing this out now that it is documented (thanks again).  Incidentally, it looks like the screenshot link for your Atom Package broke at some point :(

**Comment by BastienAr** [comment]
Yep, it was a problem in the url, should be ok now. Thanks you.
