### ISSUE TITLE
Operation timed out after 10000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by danghoaidanh** [svanoort/pyresttest#181]
Hello Pytesttest team,

Thanks for your help!

The failure symptom is that "Operation timed out after 10000 milliseconds with 0 bytes received". Is there any way to wait for the response from server?

+++++++++++++++LOG++++++++++++++
ERROR:Test Failed: Create new domain after getting the access token URL=thisIsUrl Group=Account HTTP Status Code: None
ERROR:Test Failure, failure type: Curl Exception, Reason: Curl Exception: (28, 'Operation timed out after 10000 milliseconds with 0 bytes received')
ERROR:Validator/Error details:Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pyresttest/resttest.py", line 351, in run_test
    curl.perform()  # Run the actual call
error: (28, 'Operation timed out after 10000 milliseconds with 0 bytes received')
+++++++++++END OF LOG+++++++++++
Thanks,
Danh

**Comment by spradeepv** [comment]
@danghoaidanh, if the actual call takes more time than the default timeout,
you can increase the timeout value as follows:

---
- config:
    - testset: "Quickstart app tests"
    - timeout: 600000


I hope this is what you were looking for!!

Regards,
Pradeep. S

**Comment by danghoaidanh** [comment]
It works thanks!

**Comment by svanoort** [comment]
Thank you, @spradeepv !
