### ISSUE TITLE
Default timeout causing issues

### ISSUE THREAD

**Issue by surekasri** [svanoort/pyresttest#185]
Trying to execute a yaml file with pyresttest which issues HTTP requests. Because of the default timeout value(10s) set in tests.py, the operation is getting timed out.

**Comment by spradeepv** [comment]
@surekasri, if the actual call takes more time than the default timeout,
you can increase the timeout value as follows:

---
- config:
    - testset: "Quickstart app tests"
    - timeout: 600000

**Comment by surekasri** [comment]
Thanks. That worked.

**Comment by spradeepv** [comment]
@surekasri : Can you please close the issue?

**Comment by svanoort** [comment]
@spradeepv Thank you! :)

**Comment by spradeepv** [comment]
@svanoort This is the third time I have answered for the same issue :). May
we should mention it in the docs, if it is not already there.

Regards,
Pradeep. S

**Comment by svanoort** [comment]
@spradeepv It is mentioned in the main README - https://github.com/svanoort/pyresttest#url-test-with-timeout - but no harm sprinking a few more mentions around since it comes up again and again.
