### ISSUE TITLE
compare content-encoding fails

### ISSUE THREAD

**Issue by thebino** [svanoort/pyresttest#189]
```
- compare: {header: "content-encoding", comparator: contains, expected: 'gzip'}
```
also the extract_test
```
- extract_test: {header: "content-encoding",  test: "exists"}
```
both ends in a invalid header name:
> ValueError: Invalid header name content-encoding

**Comment by svanoort** [comment]
This error is thrown when no header with that name is defined in the HTTP response.  In this case it means your test is failing. 

Remember that to get compressed responses, you must explicitly set the 'Accept-Encoding: deflate, gzip'  header on your request to indicate the client can accept compressed content.   You can also verify this behavior by running the corresponding curl call, with --verbose and --compresssed.

**Comment by thebino** [comment]
Thanks, gzip encoding has to be enabled first
```
- test:
    - curl_option_encoding: "gzip"
```

**Comment by svanoort** [comment]
@thebino That works, but a better way is to set the 'accept-encoding: deflate/gzip' header in the test configuration (there is a 'headers' option).
