### ISSUE TITLE
Path from the base_url will be ignored.

### ISSUE THREAD

**Issue by thebino** [svanoort/pyresttest#195]
If I want to run tests on a specific path, the pyresttest only uses the host part of the given base_url
`pyresttest https://host/path/ smoketest.yaml`

run the given config on https://host without the path.

**Comment by g-peev** [comment]
Look at [this](https://docs.python.org/2/library/urlparse.html?highlight=urlparse#urlparse.urljoin). This is the function used to join the base_url and the test urls. So to use the path base_url must end with */* and the test url shoud start without */* (so it's not relative to the root). At least for me this did the trick.
