### ISSUE TITLE
json_schema is not a named validator type

### ISSUE THREAD

**Issue by rsukla-handy** [svanoort/pyresttest#199]
I am trying to follow the test example from [here](https://github.com/svanoort/pyresttest/blob/master/examples/schema_test.yaml) to validate my schema. But I am getting an error 

```  "Name {0} is not a named validator type!".format(name))
ValueError: Name json_schema is not a named validator type!```

So I looked up the `validators.py` file but I couldn't find anything for `json_schema` ? Could you tell me how we can do the schema tests?? 

Where is the code for json_schema ? the below code is from `validators.py` file

```
register_extractor('jsonpath_mini', MiniJsonExtractor.parse)
register_extractor('header', HeaderExtractor.parse)
register_extractor('raw_body', RawBodyExtractor.parse)
register_validator('comparator', ComparatorValidator.parse)
register_validator('compare', ComparatorValidator.parse)
register_validator('assertEqual', ComparatorValidator.parse)
register_validator('extract_test', ExtractTestValidator.parse)
register_validator('assertTrue', ExtractTestValidator.parse)```

**Comment by rsukla-handy** [comment]
nevermind, seems like I was missing a library `jsonschema` :)

**Comment by svanoort** [comment]
Hi @rsukla-handy -  do you have the jsonschema library installed and available to python, [per the docs](https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md#jsonschema-validator-optional) ?

**Comment by rsukla-handy** [comment]
please close it, the issue is resolved.
