### ISSUE TITLE
could we check repsonse time in pyresttest? or is there any extension to do that

### ISSUE THREAD

**Issue by rsukla-handy** [svanoort/pyresttest#201]

**Comment by svanoort** [comment]
@rsukla-handy What do you mean?   You can set timeouts or use the Benchmark element to measure and report response time(s) (including doing aggregate statistics to collect the average or median time).

**Comment by rsukla-handy** [comment]
I want to make sure that my responses are coming within 3-4secs otherwise my test should fail

**Comment by rsukla-handy** [comment]
- config:
    - testset: "Customer Requests quote for all available frequencies"
    - timeout: 4  # response should come within 4 seconds

Seems like we can set timeout to make sure responses are coming within 4 seconds :)

**Comment by svanoort** [comment]
Sounds like you have your answer, then :)
