### ISSUE TITLE
How can you use pyresttest to test api that needs auth and create cookies?

### ISSUE THREAD

**Issue by seperman** [svanoort/pyresttest#207]
Hello,
Great library.
How can you use pyresttest to test api that needs auth and create cookies?

**Comment by svanoort** [comment]
Have you consulted the documentation?  I believe both of those questions are already answered.

**Comment by seperman** [comment]
@svanoort weirdly github does not do partial match when searching. This yields one item in your code base with the word "cookie" and I did not notice the 10 other tickets with the word.
