### ISSUE TITLE
how to display every test name and result

### ISSUE THREAD

**Issue by iyaozhen** [svanoort/pyresttest#213]
Thanks for @svanoort create this tool. It is very useful for me.
Now run result:

```
Test Group gecs SUCCEEDED: : 7/7 Tests Passed!
Test Group xp FAILED: : 0/1 Tests Passed!
```

I think It is too simple, how to display every test name and result. like this:

```
Test Group gecs SUCCEEDED: : 7/7 Tests Passed!
    test case a: Passed
    test case b: Passed
    ......
Test Group xp FAILED: : 0/1 Tests Passed!
    test case c: FAILED
```

**Comment by ewoo** [comment]
This would be extremely useful. Especially for those failed tests.

**Comment by sohamnavadiya** [comment]
Open [this link](http://pasted.co/c3c5e67f) and try to replace code on resttest.py. You will see the output as you mentioned above.

Let me know If you want any further change.

**Comment by sohamnavadiya** [comment]
see pull request #222

**Comment by mravitej** [comment]
Hey @iyaozhen, we need to change/ modify resttest.py to get customized output. first my request is same to get the output as you said after i modified resttest,py script as i need. please find the attached python file and place in the same folder (pyresttest/pyresttest/) and execute below command from the pyresttest folder
[resttest.zip](https://github.com/svanoort/pyresttest/files/1035952/resttest.zip)

sudo pytho setup.py install

**Comment by mravitej** [comment]
And output will parse to html file as well. Please let me know if any concerns 

Thanks,
Ravi Teja
