### ISSUE TITLE
Variables are not passing from one test set to another

### ISSUE THREAD

**Issue by mravitej** [svanoort/pyresttest#246]
1. Hi, I declared variables in config and iam using in below test case. the variables are not passing. iam not able to figure out the actual issue. 
- config:
    # Variables to use in the test set
    - variable_binds: {'user_id': 'ravitej', 'pass': 'L@ntr0n1x', 'auth': 'plain'}

- test: # Project: User Login success
    - name: "Project: User login success"
    - url: "/api/login"
    - method: "POST"
    - body: '{"username": "$user_id", "password": "$pass", "authtype": "$auth"}'
    - headers: {Content-Type: application/json}
    - expected_status: [200]
    - group: "Login_User"

2. In this below case: I'm running 1st test set and I'm getting some auth_token in response this auth_token is saved to auth_key to use in another test set, but this auth_key is not passing to the 2nd test set. it was passing an empty variable. I tried all possible ways wich are posted in Github still I am getting the same problem

- test: 
    - name: "Registration"
    - url: "/api/register"
    - method: "POST"
    - body: '{"device_id": "0080", "device_key": "imAck", "device_name": "teja", "device_description": "Added By Ravi", "project_tag": "MYSTQ-16", "attributes": "{}"}'
    - headers: {Content-Type: application/json}
    - expected_status: [200]
    - group: "Register"
    - extract_binds:
        - 'auth_key': {'jsonpath_mini': 'auth_token'}

- test:
    - name: "Status"
    - url: "/api/status"
    - method: "POST"
    - body: '{"attributes": {"num_ports": "2", "model": "Phillips", "firmware_ver": "8.0.1", "ipaddress": "192.168.0.0", "rssi": "Not Available"}}'
    - headers: {Content-Type: application/json, auth_token: "$auth_key"}
    - expected_status: [200]
    - group: "Status"

Thanks in advance,
Ravi Teja

**Comment by mvitiuk** [comment]
you need to template headers

**Comment by mravitej** [comment]
Thanks @mvitiuk, it's working now.

**Comment by svanoort** [comment]
Closed as resolved
