### ISSUE TITLE
No import examples on documentation

### ISSUE THREAD

**Issue by jeanCarloMachado** [svanoort/pyresttest#26]
Im looking for import examples to reuse my configurations. I tried many ways I thought it could be done but none of that worked. It would be nice to see some examples on the URL as a mail level syntax element too.

As the wiki say:

```
There are 5 top level test syntax elements:

    url: a simple test, fetches given url via GET request and checks for good response code

```

**Comment by pcc426** [comment]
Hi there, 
I came across the same import problem mentioned above, and I've tried 
```
---
- import: miniapp-test.yaml

```
but occurred No such file or directory IOError，I'm sure the target yaml DO exists and in the same path. I've also tried absolute Path，but neither work. Any other solution?
