### ISSUE TITLE
Stable Tag

### ISSUE THREAD

**Issue by jeanCarloMachado** [svanoort/pyresttest#33]
I need a stable version to use on my project. Till now I was using master but it eventually breaks and my Jenkins go crazy.

**Comment by svanoort** [comment]
What's breaking on master?  I'd like to get this fixed promptly, since that is intended to be a stable, tested base. 

Versions released to pip should always be stable (if I find issues, I immediately release a new one). 
Once any issues on master are fixed, I'll cut a 'stable' branch for base use.

**Comment by svanoort** [comment]
I've run through existing tests, and am not seeing any issues... what's having problems?

**Comment by svanoort** [comment]
@jeanCarloMachado ^ If you would please answer the above, I canl fix the issue or issues and hand over a stable branch for build use (reflected integration/deploy tested release states only). Thanks!

**Comment by jeanCarloMachado** [comment]
Sorry by the delay. There was some problems on the json.path.mini on that patch but it seems to be right on the current version.

**Comment by svanoort** [comment]
Created "stable" branch and have started tagging release versions.
