### ISSUE TITLE
Extract data from header and use in subsequent calls

### ISSUE THREAD

**Issue by noorbakerally** [svanoort/pyresttest#34]
Is it possible to get the authorization header from the response and use it in subsequent requests ?

**Comment by svanoort** [comment]
Certainly!  This can be done with a [header extractor](https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md#extractor-header):

**Add this to your test to extract the header from the response and use in future tests with variable 'auth_value':**
```yaml
- extract_binds:
        - 'auth_value': {'header: 'auth_header_name'}
```

**Comment by noorbakerally** [comment]
Nopes, not working, getting this error:

ValueError: Extractor header is not a valid extractor type

with the following definition:

- extract_binds:
        - 'auth_value': {header: 'Authorization'}

**Comment by svanoort** [comment]
Ah, that error you're seeing is because the version you are using does not support this feature yet. 

It was just added 1/25 to the master, so you may have to clone the latest, or if you prefer to have a version from PyPi, I should be finished testing and have one pushed by this weekend.

**Comment by svanoort** [comment]
@noorbakerally: I've released this version on PyPi, so you no longer need to clone the repo & install from that to get this feature.  Please open an issue if it misbehaves (this is still considered to be a beta feature, although of course it has plenty of test coverage).
