### ISSUE TITLE
Testing posting form data?

### ISSUE THREAD

**Issue by Jonovono** [svanoort/pyresttest#37]
Hi. I want to be able to test posting form data fields.

For example in postman you would click form-data and fill in the keys/values.

How can I do it with pyresttest? I can't seem to get it to work.

Thanks.

**Comment by svanoort** [comment]
Hi Jonovono,
The POST body will simply be the form data, something like this:
parameter=value&also=another

Content-type on the post would be: 'multipart/form-data' or a URL encoded option. 
You may find this helpful: http://stackoverflow.com/questions/14551194/how-are-parameters-sent-in-an-http-post-request

-- Sam 


multipart/form-data
