### ISSUE TITLE
Can headers contain a template?

### ISSUE THREAD

**Issue by nirsegev** [svanoort/pyresttest#44]
I am trying to extract 'company_id' from one test and use it as header in the second test. is it possible?tx
- config:
    - testset: "test"

- test:
    - name: "create company"
    - url: "/companies"
    - method: 'POST'
    - expected_status: [500]
    - extract_binds:
        - 'company_id': {'jsonpath_mini': 'id'}
    - body: '{
          "name": "fake company"
      }'

- test:
    - name: "create application"
    - url: "/applications"
    - method: 'POST'
    - headers: {'Content-Type': 'application/json','companyId': '$company_id'}
    - body: '{
        "name": "My fifth app"
        }'

**Comment by mariusmagureanu** [comment]
Good question, I haven't tried to use templated headers but I've succesfully used templates on bodies. 
- body: {'template':'{"some_id":"$some_bound_id", "host":"localhost", "url":"some/test/url"}'}

Write a quick test, see if it actually does.

**Comment by svanoort** [comment]
@nirsegev @mariusmagureanu Yes, you sure can do that, and I have tests verifying it works right. :-)

Syntax will look like this:
```yaml
headers: {template:{'Content-Type': 'application/json','companyId': '$company_id'}}
```

Note that all keys and values for the headers will have templating applied.

There's also [an example](https://github.com/svanoort/pyresttest/blob/master/pyresttest/content-test.yaml) in the test suite.  There should be some explanation in the docs somewhere too (if not, I need to add it).

**Comment by nirsegev** [comment]
Thanks! it works
