### ISSUE TITLE
Anyone help me to write yaml for following GET json response

### ISSUE THREAD

**Issue by ksreddy543** [svanoort/pyresttest#61]
YAML File:
===============

- config:
    - testset: "Basic tests"

- test: # create entity
    - name: "Basic get"
    - url: "/nitro/v1/config/af_config_info"
    - auth_username: "testuser"
    - auth_password: "testuser"
    - validators:
        - extract_test: {jsonpath_mini: "0.af_config_info",  test: "exists"}

ERROR:Test Failed: Basic get URL=http://localhost:80/rest/v1/config/af_config_info Group=Default HTTP Status Code: 200
ERROR:Test Failure, failure type: Validator Failed, Reason: Extract and test validator failed on test: exists(None)
ERROR:Validator/Error details:Extractor: Extractor Type: jsonpath_mini,  Query: "0.af_config_info", Templated?: False
ERROR:Test Failure, failure type: Validator Failed, Reason: Extract and test validator failed on test: exists(None)

For the following JSON RESPONSE BODY:
=====================

{ "errorcode": 0, "message": "Done", "additionalInfo": { "cert_present": "false" }, "af_config_info": [ { "propkey": "NS_INSIGHT_LIC", "propvalue": "1" }, { "propkey": "CB_DEPLOYMENT", "propvalue": "FALSE" }, { "propkey": "NS_DEPLOYMENT", "propvalue": "TRUE" }, { "propkey": "CR_ENABLED", "propvalue": "0" }, { "propkey": "SLA_ENABLED", "propvalue": "1" }, { "propkey": "URL_COLLECTION_ENABLED", "propvalue": "1" }, { "propkey": "HTTP_DOMAIN_ENABLED", "propvalue": "1" }, { "propkey": "USER_AGENT_ENABLED", "propvalue": "1" }, { "propkey": "HTTP_REQ_METHOD_ENABLED", "propvalue": "1" }, { "propkey": "HTTP_RESP_STATUS_ENABLED", "propvalue": "1" }, { "propkey": "OPERATING_SYSTEM_ENABLED", "propvalue": "1" }, { "propkey": "REPORT_TIMEZONE", "propvalue": "local" }, { "propkey": "SERVER_UTC_TIME", "propvalue": "1438947611" }, { "propkey": "MEDIA_TYPE_ENABLED", "propvalue": "1" }, { "propkey": "CONTENT_TYPE_ENABLED", "propvalue": "1" } ] }

**Comment by mariusmagureanu** [comment]
Given your test above, I guess it's a normal behaviour for it to fail, since you don't have this string in your response body: ```0.af_config_info``` instead you have ```af_config_info```

I suggest you start simple and test that ```errorcode``` and ```Done``` tags are found in your response and that they have your required values. You could use the example I gave you in #60 or the example @svanoort has provided.

Going a bit further, I'm not sure that the following comparison is valid:

```- compare: {extractor: 'additionalInfo', comparator: 'str_eq', expected: "{cert_present: false}"}```

I haven't looked into validators for some while and neither in the code.

**Comment by svanoort** [comment]
It should be  af_config_info.0 for the extractor.

**Comment by svanoort** [comment]
It sounds like this solves your issues?  If not, please reply back and we will re-open the issue.

**Comment by ksreddy543** [comment]
Thanks svanoort for your inputs. My requirement is need to validate each field in the response body. for example compare NS_INSIGHT_LIC == 1 from the REST response else fail the test case. Can we achieve using this UT framework. Please explain how to define yaml file to extracts the 2nd or 3rd level nodes of json? 


{ "errorcode": 0, "message": "Done", "additionalInfo": { "cert_present": "false" }, "af_config_info": [ { "propkey": "NS_INSIGHT_LIC", "propvalue": "1" },{ "propkey": "CONTENT_TYPE_ENABLED", "propvalue": "1" } ] }

**Comment by svanoort** [comment]
To be honest, I'm not sure what you're asking here, @ksreddy543 . Maybe you could clarify? 

I can tell you that regex comparators were merged in from a community contributor yesterday, and are now live on the PyPi release cut today (installed via pip, as of 1.5.0).

**Comment by ksreddy543** [comment]
Hi Sam,

My question is can i do comparision with regex as below:
ex: usernames : testuser_123, testuser_890 etc for these users below comparator should validate the usernames as passed.

compare: {jsonpath_mini: "mps.0.username", comparator: "str_eq", expected: " testuser_* "}

++++++++++++++++++++++++++++++++++++

I am using 1.3.1 version. How can i upgrade to latest "pyresttest" to get new features ?

++++++++++++++++++++++++++++++++++++

Thanks

**Comment by svanoort** [comment]
@ksreddy543 You will need to do a "pip install Django --upgrade" if you installed from pip.  If you installed from source, you will need to reinstall from source. 

Documentation on the regex function is [here](https://github.com/svanoort/pyresttest/blob/master/advanced_guide.md#comparator-functions). 

Syntax for that validator will look like: 
```yaml
compare: {jsonpath_mini: "mps.0.username", comparator: "regex", expected: " testuser_* "}
```
