### ISSUE TITLE
Test Result summary

### ISSUE THREAD

**Issue by ksreddy543** [svanoort/pyresttest#67]
@svanoort : we are looking for complete automation suite with multiple yaml files and with testcase ID's
and can we get one summary for all the YAML files at one place.

**Comment by svanoort** [comment]
@ksreddy543 This is provided my the [import element](https://github.com/svanoort/pyresttest#import-example): you can run multiple test sets by defining a parent test file that imports all child files.

**Comment by ksreddy543** [comment]
Yes.. It is working... Thanks
