### ISSUE TITLE
Could not get the cookies from http response

### ISSUE THREAD

**Issue by Sherry-sh** [svanoort/pyresttest#70]
Hi,
We've been trying to use pyresttest for testing a web application, but we couldn't get the cookie through the header extracts

    - headers: {Content-Type: application/json}
    - extract_binds:
              - 'Set-Cookie': { header: 'Set-cookie'}

but we could not get any Results

Could someone please explain why this happens and how I could fix the above example to make it work?

**Comment by Sherry-sh** [comment]
--verbose command:

* Hostname was NOT found in DNS cache
*   Trying 172.173.1.216...
* Connected to 172.173.1.216 (172.173.1.216) port 80 (#0)
> POST /api/user/login HTTP/1.1
User-Agent: PycURL/7.19.3 libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3
Host: 172.173.1.216
Accept: */*
Content-Type:application/json
Connection: close
Content-Length: 48

< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: None
< Content-Length: 95
< Content-Type: text/html; charset=UTF-8
< Set-Cookie: sid="!uoEbeRG4Mn4BDaQusNfyLA==?gASVJAAAAAAAAACMA3NpZJSMGDU1ZTYxYTMxMDhiODA1MGJiNTgxMGEwY5SGlC4="; Path=/
< Connection: close

**Comment by svanoort** [comment]
This has been belatedly fixed (with tests) by this commit: https://github.com/svanoort/pyresttest/commit/29ec38a888e4c647eeb2b33b363d3553a3646587
