### ISSUE TITLE
Generic: Support direct mapping of curl parameters if not explicitly configured - (Was: Follow redirect?)

### ISSUE THREAD

**Issue by davidkurkov** [svanoort/pyresttest#73]
Is it possible to follow a url redirect using pyresttest?

**Comment by svanoort** [comment]
Not currently; the curl/pycurl FOLLOWLOCATION option doesn't have a binding, though it would be trivial to add one.

**Comment by svanoort** [comment]
@davidkurkov I'm converting this to a more generic form, which would enable broader functionality and catch curl options that don't have defined configuration in pyresttest yet.

Options would be on tests/benchmarks, with format like so:
```yaml
---
- test: 
  - name: bob
  - curl_option_followlocation: true
  - curl_option_moremagic: true
```
Internally, every curl_option is capitalized and converted on parsing to a test/benchmark config setting.  
'curloption_optionname' which becomes curl.setopt(curl.OPTIONNAME, value).  

Some sort of inspection of legitimate curl options would be desirable at parsetime to avoid test runtime errors.  The following works (tested) but is a bit clunky

```python
democurl = pycurl.Curl()  # Actually must have a concrete instance
optionname = 'curloption_followlocation'
curlopt = optionname.lstrip('curloption_').upper()
if getattr(democurl, curlopt):
  pass # Set config variable, which will use this with setopt
else :
  raise Error("Invalid curl option given:  "+curlopt)
```

**Comment by davidkurkov** [comment]
Thank you @svanoort!

**Comment by svanoort** [comment]
@davidkurkov By the way, it's slotted into the 1.6.0 release, which is slated to be out on PIP in a week or so:  https://github.com/svanoort/pyresttest/milestones/Release%201.6.0

Current in-progress code here: https://github.com/svanoort/pyresttest/pull/83

So... available for full use soon! :santa:

**Comment by svanoort** [comment]
@davidkurkov Available now in a beta state, as of: https://github.com/svanoort/pyresttest/pull/88
